export const SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const UNSELECT_PRODUCT = "UNSELECT_PRODUCT";

export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";
export const FETCH_PRODUCTS_FROM_DB = "FETCH_PRODUCTS_FROM_DB";
export const ADD_PRODUCT = "ADD_PRODUCT";

//CART ACTIONS

export const TRANSACTION_START = "TRANSACTION_START";

//Fetch Products In Cart
export const FETCH_PRODUCTS_IN_CART_SUCCESS = "FETCH_PRODUCTS_IN_CART_SUCCESS";
export const FETCH_PRODUCTS_IN_CART_FAIL = "FETCH_PRODUCTS_IN_CART_FAIL";

//Add Product

export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_FAIL = "ADD_PRODUCT_TO_CART_FAIL";

export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY";

//Remove Product

export const REMOVE_PRODUCT_FROM_CART_SUCCESS =
  "REMOVE_PRODUCT_FROM_CART_SUCCESS";
export const REMOVE_PRODUCT_FROM_CART_FAIL = "REMOVE_PRODUCT_FROM_CART_FAIL";
