export const SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const UNSELECT_PRODUCT = "UNSELECT_PRODUCT";

export const FETCH_PRODUCTS_IN_CART_FAIL = "FETCH_PRODUCTS_IN_CART_FAIL";
export const FETCH_PRODUCTS_IN_CART_SUCCESS = "FETCH_PRODUCTS_IN_CART_SUCCESS";
export const FETCH_PRODUCTS_IN_CART = "FETCH_PRODUCTS_IN_CART";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";

//CART ACTIONS

export const TRANSACTION_START = "TRANSACTION_START";
export const TRANSACTION_FAIL = "TRANSACTION_FAIL";

// Filter Products Process
export const FILTER_PRODUCTS_FAIL = "FILTER_PRODUCTS_FAIL";
export const FILTER_PRODUCTS_SUCCESS = "FILTER_PRODUCTS_SUCCESS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const FORMAT_PRODUCTS_IN_CATALOG = "FORMAT_PRODUCTS_IN_CATALOG";

export const FETCH_PRODUCT = "FETCH_PRODUCT";
//Add Product

export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const FORMAT_DATA_IN_CART = "FORMAT_DATA_IN_CART";

export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY";

//Remove Product

export const REMOVE_PRODUCT_FROM_CART_SUCCESS =
  "REMOVE_PRODUCT_FROM_CART_SUCCESS";
export const REMOVE_PRODUCT_FROM_CART_FAIL = "REMOVE_PRODUCT_FROM_CART_FAIL";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";

export const CHANGE_PAGE_CATALOG = "CHANGE_PAGE_CATALOG";
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
